export type ServiceEntry = {
  id: string
  name: string
  category: "for_your_little_ones" | "mumz_support" | "mumz_health" | "tools"
  status: "live" | "staging" | "in_design" | "planned" | "ksa_expansion"
  description: string
  production_url: string | null
  production_url_ar: string | null
  staging_url: string | null
  staging_url_ar: string | null
  figma_url: string | null
  jira_epic: string | null
  confluence_url: string | null
  design_status: "finalized" | "in_progress" | "not_started" | "needs_update"
  design_url: string | null
  tech_owner: string
  business_owner: string
  regions: string[]
  launch_date: string | null
  notes: string | null
  vendor_tool_url: string | null
}

const FIGMA_BASE = "https://www.figma.com/design/xnZ5ToM2zq5pZXzFP7lzBE/Apps-2.0-%F0%9F%9A%A7"

const repositoryData: ServiceEntry[] = [
  {
    id: "babysitter-nannies",
    name: "Babysitter / Nannies",
    category: "for_your_little_ones",
    status: "live",
    description: "Background-checked, first-aid certified babysitters for flexible bookings",
    production_url: "https://nannies.mumzworld.com/en",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=101188-82763`,
    jira_epic: "SQ5-460",
    confluence_url: null,
    design_status: "in_progress",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE", "KSA"],
    launch_date: null,
    notes: "KSA expansion in progress. New design modifications with Ranwa's input being brought to Figma.",
    vendor_tool_url: "https://nannies.mumzworld.com/en/payment-link",
  },
  {
    id: "birthday-party-planning",
    name: "Birthday / Party Planning",
    category: "for_your_little_ones",
    status: "live",
    description: "End-to-end party planning with custom themes, entertainment, decorations, and catering",
    production_url: "https://www.mumzworld.com/en/family-care",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: "SQ5-461",
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE", "KSA"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "wallpaper-installation",
    name: "Wallpaper Installation",
    category: "for_your_little_ones",
    status: "live",
    description: "Baby-safe, nursery-ready wallpaper installation with 200+ designs",
    production_url: "https://wallpaper.mumzworld.com",
    production_url_ar: null,
    staging_url: "https://wallpaper.mumzstage.com/en",
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=101188-82763`,
    jira_epic: "SQ5-472",
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: "2026-02-04",
    notes: "AUH expansion planned. GA tags set up.",
    vendor_tool_url: "https://wallpaper.mumzstage.com/en/payment-link",
  },
  {
    id: "kids-interior-nursery",
    name: "Kids Interior / Nursery Room Design",
    category: "for_your_little_ones",
    status: "staging",
    description: "Professional kids room and nursery interior design service",
    production_url: "https://kids-nursery-room.services.mumzworld.com/en",
    production_url_ar: "https://kids-nursery-room.services.mumzworld.com/ar",
    staging_url: "https://kids-nursery-room.mumzstage.com/en",
    staging_url_ar: "https://kids-nursery-room.mumzstage.com/ar",
    figma_url: `${FIGMA_BASE}?node-id=101188-82763`,
    jira_epic: null,
    confluence_url: null,
    design_status: "in_progress",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: "Content enhancements complete. Awaiting Massi approval for go-live. Strapi URLs ready.",
    vendor_tool_url: null,
  },
  {
    id: "tutor-at-home",
    name: "Tutor at Home",
    category: "for_your_little_ones",
    status: "staging",
    description: "In-home tutoring services for children",
    production_url: "https://tutor-at-home.services.mumzworld.com/en",
    production_url_ar: null,
    staging_url: "https://tutor-at-home.mumzstage.com/en",
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=101188-82763`,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: "Dev done, similar to nannies. Ready for go-live.",
    vendor_tool_url: null,
  },
  {
    id: "home-cleaning",
    name: "Home Cleaning",
    category: "mumz_support",
    status: "live",
    description: "Professional eco-friendly, child-safe deep cleaning by trained experts",
    production_url: "https://www.mumzworld.com/en/family-care",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "gear-refresh",
    name: "Gear Refresh",
    category: "mumz_support",
    status: "live",
    description: "Specialized sanitization and cleaning for car seats, strollers, and baby gear",
    production_url: "https://www.mumzworld.com/en/family-care",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "healthy-home",
    name: "Healthy Home",
    category: "mumz_support",
    status: "live",
    description: "Pest control, disinfection, and air purification services",
    production_url: "https://www.mumzworld.com/en/family-care",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: "SQ5-473",
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: "AUH expansion planned. KSA expansion lower priority.",
    vendor_tool_url: null,
  },
  {
    id: "online-doctor-telehealth",
    name: "Online Doctor / Telehealth",
    category: "mumz_health",
    status: "live",
    description: "24/7 online doctor consultations, accessible from home",
    production_url: "https://telehealth.mumzworld.com/en-SA",
    production_url_ar: "https://telehealth.mumzworld.com/ar-sa",
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Aamir",
    business_owner: "Shady",
    regions: ["UAE", "KSA"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "doctor-at-home-flu-vaccine",
    name: "Doctor at Home / Flu Vaccine",
    category: "mumz_health",
    status: "live",
    description: "Licensed doctors visiting your home for check-ups, consultations, and vaccinations",
    production_url: "https://doctor-at-home.services.mumzworld.com/en/flu-vaccine",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "ilik-health-skincare",
    name: "Ilik Health (Skincare)",
    category: "mumz_health",
    status: "live",
    description: "Personalized prescription skincare service with consultation and custom formula",
    production_url: "https://www.mumzworld.com/en/family-care",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "midwife-services",
    name: "Midwife Services",
    category: "mumz_health",
    status: "planned",
    description: "Professional midwife services including breastfeeding support, antenatal and postnatal care",
    production_url: null,
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "in_progress",
    design_url: null,
    tech_owner: "TBD",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: "Breastfeeding + Antenatal + Postnatal + Lactation + Baby Massage. Lower priority this sprint.",
    vendor_tool_url: null,
  },
  {
    id: "services-landing-page",
    name: "Services Landing Page",
    category: "tools",
    status: "live",
    description: "Main services landing page on mumzworld.com",
    production_url: "https://www.mumzworld.com/en/services-for-mumz",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: `${FIGMA_BASE}?node-id=0-1`,
    jira_epic: null,
    confluence_url: null,
    design_status: "needs_update",
    design_url: null,
    tech_owner: "Raneesh (Strapi)",
    business_owner: "Shady",
    regions: ["UAE", "KSA"],
    launch_date: null,
    notes: "UX issues: zero social proof, FAQ gaps, missing content marketing, help CTA not visible",
    vendor_tool_url: null,
  },
  {
    id: "services-financial-dashboard",
    name: "Services Financial Dashboard",
    category: "tools",
    status: "live",
    description: "Financial analytics dashboard for services vertical",
    production_url: "https://services-dashboard.mumzdesk.com",
    production_url_ar: null,
    staging_url: null,
    staging_url_ar: null,
    figma_url: null,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Sabeur",
    business_owner: "Akshay",
    regions: ["UAE", "KSA"],
    launch_date: null,
    notes: null,
    vendor_tool_url: null,
  },
  {
    id: "vendor-payment-tool",
    name: "Vendor Payment Link Generator",
    category: "tools",
    status: "live",
    description: "Tool for vendors to fill service data and generate payment links for customers",
    production_url: "https://wallpaper.mumzworld.com/en/payment-link",
    production_url_ar: null,
    staging_url: "https://wallpaper.mumzstage.com/en/payment-link",
    staging_url_ar: null,
    figma_url: null,
    jira_epic: null,
    confluence_url: null,
    design_status: "finalized",
    design_url: null,
    tech_owner: "Mustafa",
    business_owner: "Shady",
    regions: ["UAE"],
    launch_date: null,
    notes: "Requires Strapi authentication. Used by vendors to generate payment links per service.",
    vendor_tool_url: "https://wallpaper.mumzstage.com/en/payment-link",
  },
]

export function getRepositoryData(): ServiceEntry[] {
  return repositoryData
}
