export type SeedCategory = {
  name: string
  slug: string
  items: SeedItem[]
}

export type SeedItem = {
  item_number: string
  title: string
  workstream: string
  owners: string[]
  status: string
  priority: string | null
  eta: string | null
  source: string | null
  sprint: string | null
  details: string | null
  expected_impact: string | null
  sheet_tab: string
}

export function getSeedData(): SeedCategory[] {
  return [
    // =========================================================================
    // SERVICES ENHANCEMENT TAB (Main Tracker) - 31 items
    // =========================================================================
    {
      name: 'Babysitter/Nanny',
      slug: 'babysitter-nanny',
      items: [
        {
          item_number: 'SE-1',
          title: 'Update trusted text and banner copy',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Update the trusted text and banner copy on babysitter/nanny landing page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-2',
          title: 'Tailored care section redesign',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Redesign the tailored care section for babysitter landing page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-3',
          title: 'Moment for mom section',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add moment for mom section to babysitter landing page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-4',
          title: 'Images/Icons update for babysitter page',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Update images and icons across the babysitter/nanny page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-5',
          title: 'Review content for babysitter page',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Content review pass on babysitter landing page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-6',
          title: 'Dev + Launch babysitter redesign',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Develop and launch the redesigned babysitter page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-7',
          title: 'Send design for babysitter page review',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Share final design files for babysitter page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-8',
          title: 'Incorporate USPs into babysitter page',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add unique selling propositions to the babysitter page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-9',
          title: 'Review combined design for babysitter page',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Final review of the combined design for babysitter page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Birthday/Party',
      slug: 'birthday-party',
      items: [
        {
          item_number: 'SE-10',
          title: 'Packages on top of birthday page',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Move packages section to the top of the birthday party page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-11',
          title: 'WhatsApp icon on birthday page',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add WhatsApp contact icon to birthday party page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-12',
          title: 'Side-by-side comparison for packages',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Create side-by-side comparison view for birthday packages',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-13',
          title: 'Edit button for birthday packages',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add edit button functionality for birthday packages',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-14',
          title: 'Carousel for birthday photos',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add photo carousel to birthday party page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-15',
          title: 'Group comparison for birthday packages',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Enable group comparison functionality for birthday packages',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-16',
          title: 'Instagram social proof on birthday page',
          workstream: 'brand',
          owners: ['Brand Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add Instagram social proof section to birthday page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-17',
          title: 'FAQ content for birthday page',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Create FAQ content for the birthday party page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-18',
          title: 'Party KSA configuration',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Configure birthday party page for KSA region',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Kids Interior',
      slug: 'kids-interior',
      items: [
        {
          item_number: 'SE-19',
          title: 'Dev + Launch kids interior page',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Develop and launch the kids interior service page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-20',
          title: 'AR copy for kids interior',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Arabic copy for kids interior page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-21',
          title: 'Content review for kids interior',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Review content for kids interior page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-22',
          title: 'Share design link for kids interior',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Share the design link for kids interior page review',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Wallpaper',
      slug: 'wallpaper',
      items: [
        {
          item_number: 'SE-23',
          title: 'Rework landing page for wallpaper',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Rework the wallpaper service landing page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-24',
          title: '3D visualization for wallpaper',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add 3D visualization feature for wallpaper service',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-25',
          title: 'Nursery sections for wallpaper',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Add nursery-specific sections to wallpaper page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-26',
          title: 'KSA configuration for wallpaper',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Configure wallpaper service for KSA region',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'HealthyHome',
      slug: 'healthyhome',
      items: [
        {
          item_number: 'SE-27',
          title: 'KSA configuration for HealthyHome',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Configure HealthyHome service for KSA region',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-28',
          title: 'Merge discussion for HealthyHome',
          workstream: 'strategy',
          owners: ['Product Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Discuss merging HealthyHome into main services flow',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-29',
          title: 'Fix thumbnails for HealthyHome',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Fix thumbnail images on HealthyHome page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
        {
          item_number: 'SE-30',
          title: 'Hero banner for HealthyHome',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Design hero banner for HealthyHome page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Midwife',
      slug: 'midwife',
      items: [
        {
          item_number: 'SE-31',
          title: 'Design midwife service page',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'in_progress',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Design the midwife service landing page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Tutor at Home',
      slug: 'tutor-at-home',
      items: [
        {
          item_number: 'SE-32',
          title: 'Go live tutor at home service',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Launch tutor at home service page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Home Cleaning',
      slug: 'home-cleaning',
      items: [
        {
          item_number: 'SE-33',
          title: 'Hero banner for home cleaning',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Design hero banner for home cleaning page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'Gear Refresh',
      slug: 'gear-refresh',
      items: [
        {
          item_number: 'SE-34',
          title: 'Hero banner for gear refresh',
          workstream: 'design',
          owners: ['Design Team'],
          status: 'done',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Design hero banner for gear refresh page',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },
    {
      name: 'General',
      slug: 'general',
      items: [
        {
          item_number: 'SE-35',
          title: 'GA Tracking for all services',
          workstream: 'tech',
          owners: ['Tech Team'],
          status: 'not_started',
          priority: null,
          eta: null,
          source: 'Services Enhancement',
          sprint: null,
          details: 'Implement GA tracking across all service pages',
          expected_impact: null,
          sheet_tab: 'Services Enhancement',
        },
      ],
    },

    // =========================================================================
    // BIRTHDAY/PARTY PLANNING DETAILED TAB - 14 items
    // =========================================================================
    {
      name: 'Birthday/Party Planning (Detailed)',
      slug: 'birthday-party-detailed',
      items: [
        {
          item_number: 'BP-1',
          title: 'Restructure packages section - move to top',
          workstream: 'design',
          owners: ['Sarah', 'Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-01',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 12',
          details: 'Move the packages comparison section to the top of the page above the fold for immediate visibility',
          expected_impact: 'Increase package selection rate by 20%',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-2',
          title: 'Add WhatsApp floating button',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-04-28',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 12',
          details: 'Add a floating WhatsApp button that connects to the birthday planning team for instant inquiries',
          expected_impact: 'Increase lead conversion by 15%',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-3',
          title: 'Side-by-side package comparison view',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-05',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 12',
          details: 'Create a side-by-side comparison table for birthday packages showing features, pricing, and inclusions',
          expected_impact: 'Reduce decision time, improve package upgrade rate by 10%',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-4',
          title: 'Edit/customize button on package cards',
          workstream: 'tech',
          owners: ['Omar', 'Fatima'],
          status: 'in_progress',
          priority: 'p1',
          eta: '2026-05-10',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 13',
          details: 'Add edit/customize button on each package card allowing users to modify package contents before inquiry',
          expected_impact: 'Increase customization requests by 25%',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-5',
          title: 'Photo carousel for past events',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-15',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 13',
          details: 'Add an image carousel showcasing past birthday events organized through the platform',
          expected_impact: 'Build trust, increase time on page by 30%',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-6',
          title: 'Group package comparison tool',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-20',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 13',
          details: 'Build interactive tool for comparing multiple packages simultaneously with checkboxes',
          expected_impact: 'Improve user decision-making experience',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-7',
          title: 'Instagram social proof integration',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-05-25',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 14',
          details: 'Embed Instagram feed showing real customer birthday party photos and testimonials',
          expected_impact: 'Increase social proof and trust signals',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-8',
          title: 'FAQ section with structured data',
          workstream: 'brand',
          owners: ['Layla', 'Content Team'],
          status: 'done',
          priority: 'p1',
          eta: null,
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 11',
          details: 'Create comprehensive FAQ section with schema markup for SEO',
          expected_impact: 'Improve SEO ranking for birthday party queries',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-9',
          title: 'KSA region birthday page setup',
          workstream: 'tech',
          owners: ['Omar', 'Ahmed'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 11',
          details: 'Configure and launch birthday party page for KSA region with localized content and pricing',
          expected_impact: 'Open KSA market for birthday services',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-10',
          title: 'Add venue filter to package selection',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-01',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 14',
          details: 'Add venue type filter (indoor/outdoor/home) to package browsing experience',
          expected_impact: 'Improve package relevance for users',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-11',
          title: 'Birthday party testimonials section',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-05',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 14',
          details: 'Add video and text testimonials from parents who used the birthday party service',
          expected_impact: 'Increase conversion through social proof',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-12',
          title: 'Age-based party theme recommendations',
          workstream: 'product',
          owners: ['Sarah', 'Content Team'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-10',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 15',
          details: 'Add age-based theme recommendations engine to help parents choose appropriate party themes',
          expected_impact: 'Improve user experience and reduce bounce rate',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-13',
          title: 'Party checklist download feature',
          workstream: 'product',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p3',
          eta: '2026-06-15',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 15',
          details: 'Offer downloadable party planning checklist as lead magnet',
          expected_impact: 'Generate leads through content marketing',
          sheet_tab: 'Birthday/Party Planning',
        },
        {
          item_number: 'BP-14',
          title: 'Multi-language support for birthday page',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p1',
          eta: '2026-05-12',
          source: 'Birthday Planning Sprint',
          sprint: 'Sprint 12',
          details: 'Full Arabic language support for birthday party page including RTL layout',
          expected_impact: 'Reach Arabic-speaking audience segment',
          sheet_tab: 'Birthday/Party Planning',
        },
      ],
    },

    // =========================================================================
    // HOME CLEANING DETAILED TAB - 10 items
    // =========================================================================
    {
      name: 'Home Cleaning (Detailed)',
      slug: 'home-cleaning-detailed',
      items: [
        {
          item_number: 'HC-1',
          title: 'Hero banner redesign for home cleaning',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 11',
          details: 'Redesign hero banner with new photography and value proposition copy',
          expected_impact: 'Improve first impression and reduce bounce rate by 15%',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-2',
          title: 'Pricing calculator widget',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-05',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 12',
          details: 'Build interactive pricing calculator based on home size, frequency, and add-on services',
          expected_impact: 'Increase booking conversion by 20% through price transparency',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-3',
          title: 'Service area coverage map',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-15',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 13',
          details: 'Interactive map showing service coverage areas with availability indicators',
          expected_impact: 'Reduce out-of-area inquiries by 40%',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-4',
          title: 'Before/after gallery for cleaning',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-20',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 13',
          details: 'Add before/after photo gallery with slider component showing cleaning results',
          expected_impact: 'Increase trust and conversion through visual proof',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-5',
          title: 'Recurring booking flow',
          workstream: 'tech',
          owners: ['Omar', 'Ahmed'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-25',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 13',
          details: 'Build recurring booking flow with weekly/biweekly/monthly options and discount tiers',
          expected_impact: 'Increase recurring bookings by 35%',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-6',
          title: 'Customer reviews integration',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-06-01',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 14',
          details: 'Integrate verified customer reviews from booking platform with star ratings',
          expected_impact: 'Build trust through authentic reviews',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-7',
          title: 'Deep cleaning add-on upsell',
          workstream: 'product',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-05',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 14',
          details: 'Add deep cleaning service upsell during standard booking flow',
          expected_impact: 'Increase average order value by 15%',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-8',
          title: 'Cleaning supplies information page',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: 'p2',
          eta: null,
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 11',
          details: 'Create content page about eco-friendly cleaning supplies used by the service',
          expected_impact: 'Address customer concerns about cleaning products',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-9',
          title: 'KSA home cleaning launch',
          workstream: 'ops',
          owners: ['Ahmed', 'Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 12',
          details: 'Launch home cleaning service in KSA with localized pricing and service providers',
          expected_impact: 'Expand to KSA market',
          sheet_tab: 'Home Cleaning',
        },
        {
          item_number: 'HC-10',
          title: 'Post-cleaning feedback flow',
          workstream: 'product',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-10',
          source: 'Home Cleaning Sprint',
          sprint: 'Sprint 15',
          details: 'Automated post-cleaning feedback collection with rating and re-booking prompt',
          expected_impact: 'Improve service quality and retention',
          sheet_tab: 'Home Cleaning',
        },
      ],
    },

    // =========================================================================
    // WALLPAPER DETAILED TAB - 10 items
    // =========================================================================
    {
      name: 'Wallpaper (Detailed)',
      slug: 'wallpaper-detailed',
      items: [
        {
          item_number: 'WP-1',
          title: 'Rework wallpaper landing page layout',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 12',
          details: 'Complete redesign of wallpaper landing page with new hero, collections grid, and room visualizer CTA',
          expected_impact: 'Increase engagement and reduce bounce rate by 25%',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-2',
          title: '3D room visualization tool',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-30',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 13',
          details: 'Build 3D room visualization tool allowing customers to see wallpaper in their room using uploaded photos',
          expected_impact: 'Major differentiator, expected 30% increase in conversion',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-3',
          title: 'Nursery wallpaper collection section',
          workstream: 'design',
          owners: ['Sarah', 'Layla'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-15',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 13',
          details: 'Add dedicated nursery wallpaper section with age-appropriate collections and safety info',
          expected_impact: 'Capture nursery decoration market segment',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-4',
          title: 'KSA wallpaper service configuration',
          workstream: 'tech',
          owners: ['Omar', 'Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-05',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 12',
          details: 'Configure wallpaper service for KSA including local installer network and pricing in SAR',
          expected_impact: 'Expand wallpaper service to KSA market',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-5',
          title: 'Wallpaper collection filtering and search',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-20',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 13',
          details: 'Add advanced filtering by room type, color, pattern, and style with search functionality',
          expected_impact: 'Improve discovery and reduce time to selection',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-6',
          title: 'Sample ordering flow',
          workstream: 'product',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-06-01',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 14',
          details: 'Allow customers to order physical wallpaper samples before committing to full purchase',
          expected_impact: 'Reduce returns and increase customer confidence',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-7',
          title: 'Installation guide content',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: 'p2',
          eta: null,
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 11',
          details: 'Create professional installation guide content with video tutorials',
          expected_impact: 'Reduce installation-related customer support queries',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-8',
          title: 'Wallpaper calculator tool',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-25',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 13',
          details: 'Build calculator to estimate wallpaper rolls needed based on room dimensions',
          expected_impact: 'Reduce ordering errors and improve customer experience',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-9',
          title: 'Designer collaboration feature',
          workstream: 'product',
          owners: ['Sarah', 'Fatima'],
          status: 'not_started',
          priority: 'p3',
          eta: '2026-06-15',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 15',
          details: 'Allow customers to consult with interior designers for wallpaper selection',
          expected_impact: 'Premium service offering with higher margins',
          sheet_tab: 'Wallpaper',
        },
        {
          item_number: 'WP-10',
          title: 'Wallpaper trending collections',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'in_progress',
          priority: 'p2',
          eta: '2026-05-10',
          source: 'Wallpaper Sprint',
          sprint: 'Sprint 12',
          details: 'Curate and showcase trending wallpaper collections based on seasonal themes',
          expected_impact: 'Drive engagement through curated content',
          sheet_tab: 'Wallpaper',
        },
      ],
    },

    // =========================================================================
    // GEAR REFRESH DETAILED TAB - 11 items
    // =========================================================================
    {
      name: 'Gear Refresh (Detailed)',
      slug: 'gear-refresh-detailed',
      items: [
        {
          item_number: 'GR-1',
          title: 'Hero banner for gear refresh page',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 11',
          details: 'Design hero banner highlighting the gear refresh value proposition and sustainability angle',
          expected_impact: 'Strong first impression for gear refresh service',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-2',
          title: 'Gear condition assessment flow',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-08',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 12',
          details: 'Build step-by-step gear condition assessment with photo upload for accurate pricing',
          expected_impact: 'Streamline valuation process, reduce back-and-forth by 50%',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-3',
          title: 'Pricing engine for used gear',
          workstream: 'tech',
          owners: ['Omar', 'Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-12',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 12',
          details: 'Develop pricing engine based on gear type, brand, condition, and market data',
          expected_impact: 'Automate pricing, reduce manual effort by 70%',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-4',
          title: 'Gear pickup scheduling',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-20',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 13',
          details: 'Self-service pickup scheduling with time slot selection and driver assignment',
          expected_impact: 'Improve operational efficiency and customer convenience',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-5',
          title: 'Gear catalog browsing page',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-25',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 13',
          details: 'Design catalog page for browsing available refurbished gear with filters',
          expected_impact: 'Enable buyer-side marketplace experience',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-6',
          title: 'Sustainability impact tracker',
          workstream: 'product',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-01',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 14',
          details: 'Show environmental impact of gear refresh (items saved from landfill, CO2 saved)',
          expected_impact: 'Strengthen brand sustainability messaging',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-7',
          title: 'Gear refresh brand partnerships',
          workstream: 'strategy',
          owners: ['Ahmed', 'Layla'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-05',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 14',
          details: 'Establish partnerships with baby gear brands for certified refurbishment programs',
          expected_impact: 'Add premium tier to gear refresh service',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-8',
          title: 'Trade-in credit system',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-30',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 14',
          details: 'Build trade-in credit system where sellers get store credit for new purchases',
          expected_impact: 'Increase cross-selling and customer retention',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-9',
          title: 'Quality assurance checklist display',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: 'p1',
          eta: null,
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 11',
          details: 'Display the QA checklist performed on each item to build buyer confidence',
          expected_impact: 'Increase buyer trust in refurbished items',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-10',
          title: 'Gear refresh KSA expansion',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-06-10',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 15',
          details: 'Expand gear refresh service to KSA with local logistics partners',
          expected_impact: 'Open KSA market for gear refresh',
          sheet_tab: 'Gear Refresh',
        },
        {
          item_number: 'GR-11',
          title: 'Seller dashboard for gear tracking',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-15',
          source: 'Gear Refresh Sprint',
          sprint: 'Sprint 15',
          details: 'Dashboard for sellers to track gear status from pickup to sale with payment tracking',
          expected_impact: 'Improve seller experience and transparency',
          sheet_tab: 'Gear Refresh',
        },
      ],
    },

    // =========================================================================
    // TELECONSULTATION DETAILED TAB - 11 items
    // =========================================================================
    {
      name: 'Teleconsultation (Detailed)',
      slug: 'teleconsultation-detailed',
      items: [
        {
          item_number: 'TC-1',
          title: 'Teleconsultation landing page redesign',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-05',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 12',
          details: 'Redesign teleconsultation landing page with specialist categories, booking flow, and trust signals',
          expected_impact: 'Increase booking conversion by 25%',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-2',
          title: 'Doctor profile pages',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 12',
          details: 'Build individual doctor profile pages with credentials, availability, and patient reviews',
          expected_impact: 'Build trust and help parents choose the right specialist',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-3',
          title: 'Real-time availability calendar',
          workstream: 'tech',
          owners: ['Omar', 'Fatima'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-20',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 13',
          details: 'Live availability calendar synced with doctor schedules for instant booking',
          expected_impact: 'Reduce booking friction, increase same-day consultations by 40%',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-4',
          title: 'Video consultation platform integration',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-15',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 12',
          details: 'Integrate video consultation platform with waiting room, recording, and prescription features',
          expected_impact: 'Enable seamless teleconsultation experience',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-5',
          title: 'Specialty filter and search',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-25',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 13',
          details: 'Add filtering by specialty (pediatrics, lactation, nutrition, mental health) with search',
          expected_impact: 'Help parents find the right specialist quickly',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-6',
          title: 'Post-consultation follow-up system',
          workstream: 'product',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-06-01',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 14',
          details: 'Automated follow-up system with prescription reminders and follow-up booking prompts',
          expected_impact: 'Increase follow-up bookings by 30%',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-7',
          title: 'Insurance integration research',
          workstream: 'strategy',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-10',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 14',
          details: 'Research and plan integration with major insurance providers for direct billing',
          expected_impact: 'Remove cost barrier for insured families',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-8',
          title: 'Teleconsultation FAQ and help center',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: 'p1',
          eta: null,
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 11',
          details: 'Create comprehensive FAQ and help content for teleconsultation service',
          expected_impact: 'Reduce support queries and increase user confidence',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-9',
          title: 'KSA teleconsultation licensing setup',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-15',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 12',
          details: 'Set up licensing and compliance for teleconsultation service in KSA',
          expected_impact: 'Enable legal operation in KSA market',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-10',
          title: 'Patient history and records access',
          workstream: 'tech',
          owners: ['Omar', 'Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-06-05',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 14',
          details: 'Allow doctors to access patient consultation history during appointments',
          expected_impact: 'Improve consultation quality and continuity of care',
          sheet_tab: 'Teleconsultation',
        },
        {
          item_number: 'TC-11',
          title: 'Teleconsultation rating and review system',
          workstream: 'product',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-15',
          source: 'Teleconsultation Sprint',
          sprint: 'Sprint 15',
          details: 'Post-consultation rating system with review moderation and doctor performance tracking',
          expected_impact: 'Build trust through verified patient reviews',
          sheet_tab: 'Teleconsultation',
        },
      ],
    },

    // =========================================================================
    // SERVICES HOMEPAGE TAB - 4 items
    // =========================================================================
    {
      name: 'Services Homepage',
      slug: 'services-homepage',
      items: [
        {
          item_number: 'SH-1',
          title: 'Restructure services homepage layout',
          workstream: 'design',
          owners: ['Sarah', 'Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'Services Homepage',
          sprint: 'Sprint 12',
          details: 'Complete restructure of services homepage with new category grid, featured services, and personalized recommendations',
          expected_impact: 'Improve service discovery and cross-sell rates by 20%',
          sheet_tab: 'Services Homepage',
        },
        {
          item_number: 'SH-2',
          title: 'Journey-based navigation structure',
          workstream: 'product',
          owners: ['Fatima', 'Sarah'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-20',
          source: 'Services Homepage',
          sprint: 'Sprint 13',
          details: 'Implement journey-based navigation (pregnancy, newborn, toddler, school-age) instead of service-based categories',
          expected_impact: 'Better match services to parent lifecycle stage',
          sheet_tab: 'Services Homepage',
        },
        {
          item_number: 'SH-3',
          title: 'Services homepage A/B test setup',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-25',
          source: 'Services Homepage',
          sprint: 'Sprint 13',
          details: 'Set up A/B testing framework for services homepage to test different layouts and CTAs',
          expected_impact: 'Data-driven optimization of homepage conversion',
          sheet_tab: 'Services Homepage',
        },
        {
          item_number: 'SH-4',
          title: 'Popular services section with social proof',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-30',
          source: 'Services Homepage',
          sprint: 'Sprint 14',
          details: 'Add popular services section showing booking counts, ratings, and recent reviews',
          expected_impact: 'Increase conversion through social proof and urgency',
          sheet_tab: 'Services Homepage',
        },
      ],
    },

    // =========================================================================
    // HEALTHYHOME MERGE TAB - 10 items
    // =========================================================================
    {
      name: 'HealthyHome Merge',
      slug: 'healthyhome-merge',
      items: [
        {
          item_number: 'HM-1',
          title: 'HealthyHome merge strategy document',
          workstream: 'strategy',
          owners: ['Ahmed'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'HealthyHome Merge',
          sprint: 'Sprint 11',
          details: 'Define the strategy for merging HealthyHome into the main services platform',
          expected_impact: 'Clear roadmap for HealthyHome integration',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-2',
          title: 'HealthyHome service mockups in new design system',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-08',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 12',
          details: 'Create mockups for HealthyHome services using the new unified design system',
          expected_impact: 'Visual consistency across all services',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-3',
          title: 'Fix HealthyHome service thumbnails',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p1',
          eta: '2026-05-05',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 12',
          details: 'Fix broken and inconsistent thumbnail images across HealthyHome service pages',
          expected_impact: 'Improve visual quality of HealthyHome listings',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-4',
          title: 'Migrate HealthyHome content to CMS',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-15',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 13',
          details: 'Migrate all HealthyHome service content to the unified CMS platform',
          expected_impact: 'Enable content management from single platform',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-5',
          title: 'HealthyHome URL redirect mapping',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-12',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 12',
          details: 'Create URL redirect map from old HealthyHome URLs to new merged service URLs',
          expected_impact: 'Preserve SEO value and prevent broken links',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-6',
          title: 'HealthyHome booking flow integration',
          workstream: 'tech',
          owners: ['Fatima', 'Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-25',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 13',
          details: 'Integrate HealthyHome booking flow into the unified services booking system',
          expected_impact: 'Unified booking experience across all services',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-7',
          title: 'HealthyHome KSA configuration',
          workstream: 'tech',
          owners: ['Omar', 'Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 12',
          details: 'Configure HealthyHome services for KSA region with localized content',
          expected_impact: 'Expand HealthyHome to KSA market',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-8',
          title: 'HealthyHome service provider onboarding',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-30',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 14',
          details: 'Onboard HealthyHome service providers to the unified provider management system',
          expected_impact: 'Streamline provider management',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-9',
          title: 'HealthyHome analytics migration',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-05',
          source: 'HealthyHome Merge',
          sprint: 'Sprint 14',
          details: 'Migrate HealthyHome analytics to unified analytics platform with historical data preservation',
          expected_impact: 'Unified reporting across all services',
          sheet_tab: 'HealthyHome Merge',
        },
        {
          item_number: 'HM-10',
          title: 'HealthyHome hero banner update',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'done',
          priority: 'p1',
          eta: null,
          source: 'HealthyHome Merge',
          sprint: 'Sprint 11',
          details: 'Update HealthyHome hero banner to match new design system',
          expected_impact: 'Visual consistency during merge transition',
          sheet_tab: 'HealthyHome Merge',
        },
      ],
    },

    // =========================================================================
    // BABYSITTER DETAILED TAB - 14 items
    // =========================================================================
    {
      name: 'Babysitter (Detailed)',
      slug: 'babysitter-detailed',
      items: [
        {
          item_number: 'BS-1',
          title: 'Babysitter landing page full redesign',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-08',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 12',
          details: 'Complete redesign of the babysitter landing page with new layout, photography, and content structure',
          expected_impact: 'Increase booking conversion by 25%',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-2',
          title: 'Babysitter USP section with icons',
          workstream: 'design',
          owners: ['Sarah', 'Layla'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'Babysitter Sprint',
          sprint: 'Sprint 11',
          details: 'Design USP section with custom icons highlighting key differentiators (vetted, trained, insured)',
          expected_impact: 'Clearly communicate value proposition',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-3',
          title: 'WhatsApp booking integration for babysitter',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-05',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 12',
          details: 'Add WhatsApp click-to-chat with pre-filled message for babysitter booking inquiries',
          expected_impact: 'Increase inquiry conversion by 20%',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-4',
          title: 'Babysitter CTA optimization',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-03',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 12',
          details: 'Optimize CTA placement and copy throughout the babysitter page for higher click-through',
          expected_impact: 'Increase CTA click-through rate by 15%',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-5',
          title: 'Babysitter filtering by specialization',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-15',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 13',
          details: 'Add filtering options for babysitter specializations (newborn, toddler, special needs, multilingual)',
          expected_impact: 'Help parents find the right babysitter match',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-6',
          title: 'Babysitter profile cards design',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-18',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 13',
          details: 'Design babysitter profile cards showing photo, experience, specializations, and ratings',
          expected_impact: 'Build trust and help parents make informed decisions',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-7',
          title: 'Babysitter testimonials carousel',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'done',
          priority: 'p1',
          eta: null,
          source: 'Babysitter Sprint',
          sprint: 'Sprint 11',
          details: 'Add testimonials carousel with verified parent reviews and ratings',
          expected_impact: 'Increase trust through social proof',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-8',
          title: 'Babysitter safety and vetting process page',
          workstream: 'brand',
          owners: ['Content Team'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'Babysitter Sprint',
          sprint: 'Sprint 11',
          details: 'Create detailed page about the babysitter vetting, training, and safety process',
          expected_impact: 'Address primary parent concern about safety',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-9',
          title: 'Babysitter availability checker',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-22',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 13',
          details: 'Real-time availability checker for babysitters by date, time, and location',
          expected_impact: 'Reduce booking friction and abandoned inquiries',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-10',
          title: 'Babysitter pricing transparency page',
          workstream: 'product',
          owners: ['Ahmed'],
          status: 'in_progress',
          priority: 'p1',
          eta: '2026-05-10',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 12',
          details: 'Clear pricing page showing hourly/daily/weekly rates with package discounts',
          expected_impact: 'Reduce price-related inquiries and increase self-service booking',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-11',
          title: 'Babysitter emergency booking flow',
          workstream: 'tech',
          owners: ['Omar', 'Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-01',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 14',
          details: 'Fast-track booking flow for same-day babysitter requests with priority matching',
          expected_impact: 'Capture urgent booking demand',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-12',
          title: 'Babysitter KSA page localization',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-12',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 12',
          details: 'Localize babysitter page for KSA with Arabic content, local pricing, and region-specific trust signals',
          expected_impact: 'Launch babysitter service in KSA market',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-13',
          title: 'Babysitter subscription packages',
          workstream: 'product',
          owners: ['Ahmed', 'Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-10',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 15',
          details: 'Design and implement subscription-based babysitter packages (monthly hours bundles)',
          expected_impact: 'Increase customer lifetime value and retention',
          sheet_tab: 'Babysitter Detailed',
        },
        {
          item_number: 'BS-14',
          title: 'Babysitter page SEO optimization',
          workstream: 'brand',
          owners: ['Layla', 'Content Team'],
          status: 'in_progress',
          priority: 'p1',
          eta: '2026-05-08',
          source: 'Babysitter Sprint',
          sprint: 'Sprint 12',
          details: 'SEO optimization for babysitter page including meta tags, structured data, and content optimization',
          expected_impact: 'Improve organic search ranking for babysitter queries',
          sheet_tab: 'Babysitter Detailed',
        },
      ],
    },

    // =========================================================================
    // ILIK TAB - 1 item
    // =========================================================================
    {
      name: 'Ilik',
      slug: 'ilik',
      items: [
        {
          item_number: 'IL-1',
          title: 'Remove Ilik from services homepage',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-05',
          source: 'Ilik',
          sprint: 'Sprint 12',
          details: 'Remove Ilik service listing from the services homepage as the service is being discontinued',
          expected_impact: 'Clean up services homepage, remove discontinued service',
          sheet_tab: 'Ilik',
        },
      ],
    },

    // =========================================================================
    // GA/CROSS-PLATFORM TAB - 12 items
    // =========================================================================
    {
      name: 'GA/Cross-platform',
      slug: 'ga-cross-platform',
      items: [
        {
          item_number: 'GA-1',
          title: 'GA4 tracking implementation for all services',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 12',
          details: 'Implement GA4 tracking across all service pages with custom events for key user actions',
          expected_impact: 'Enable data-driven decision making for all services',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-2',
          title: 'Cross-sell widget between services',
          workstream: 'product',
          owners: ['Fatima', 'Sarah'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-20',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 13',
          details: 'Build cross-sell recommendation widget showing related services on each service page',
          expected_impact: 'Increase multi-service adoption by 15%',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-3',
          title: 'WhatsApp button standardization',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-08',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 12',
          details: 'Standardize WhatsApp floating button component across all service pages with consistent behavior and tracking',
          expected_impact: 'Consistent user experience and accurate tracking',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-4',
          title: 'UTM parameter tracking setup',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-15',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 13',
          details: 'Set up UTM parameter tracking for all marketing campaigns driving to service pages',
          expected_impact: 'Accurate attribution of marketing spend to service bookings',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-5',
          title: 'Conversion funnel tracking',
          workstream: 'tech',
          owners: ['Omar', 'Fatima'],
          status: 'not_started',
          priority: 'p0',
          eta: '2026-05-18',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 13',
          details: 'Implement conversion funnel tracking from page visit to booking completion for each service',
          expected_impact: 'Identify and fix conversion drop-off points',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-6',
          title: 'Heatmap integration for service pages',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-01',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 14',
          details: 'Integrate heatmap tracking (Hotjar/similar) to analyze user behavior on service pages',
          expected_impact: 'Visual insights into user interaction patterns',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-7',
          title: 'Cross-platform deep linking',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-25',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 13',
          details: 'Implement deep linking from mobile app to web service pages and vice versa',
          expected_impact: 'Seamless cross-platform user experience',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-8',
          title: 'Service performance dashboard',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-30',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 14',
          details: 'Build internal dashboard showing service page performance metrics (visits, conversions, revenue)',
          expected_impact: 'Real-time visibility into service performance',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-9',
          title: 'A/B testing infrastructure',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-06-05',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 14',
          details: 'Set up A/B testing infrastructure for running experiments on service pages',
          expected_impact: 'Enable data-driven optimization of all service pages',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-10',
          title: 'User session recording setup',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-10',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 15',
          details: 'Set up session recording for service pages to analyze user journeys and pain points',
          expected_impact: 'Qualitative insights into user experience issues',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-11',
          title: 'Email campaign tracking integration',
          workstream: 'brand',
          owners: ['Layla'],
          status: 'not_started',
          priority: 'p2',
          eta: '2026-06-05',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 14',
          details: 'Integrate email campaign tracking with service page analytics for full journey tracking',
          expected_impact: 'Complete view of email-to-conversion funnel',
          sheet_tab: 'GA/Cross-platform',
        },
        {
          item_number: 'GA-12',
          title: 'Push notification analytics',
          workstream: 'tech',
          owners: ['Omar'],
          status: 'not_started',
          priority: 'p3',
          eta: '2026-06-15',
          source: 'GA/Cross-platform',
          sprint: 'Sprint 15',
          details: 'Track push notification engagement and its impact on service page visits and bookings',
          expected_impact: 'Optimize push notification strategy',
          sheet_tab: 'GA/Cross-platform',
        },
      ],
    },

    // =========================================================================
    // GOVERNANCE TAB - 8 items
    // =========================================================================
    {
      name: 'Governance',
      slug: 'governance',
      items: [
        {
          item_number: 'GOV-1',
          title: 'Weekly PMO review cadence setup',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'done',
          priority: 'p0',
          eta: null,
          source: 'Governance',
          sprint: 'Sprint 11',
          details: 'Establish weekly PMO review meeting cadence with agenda template and stakeholder alignment',
          expected_impact: 'Consistent project oversight and accountability',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-2',
          title: 'Universal service page template',
          workstream: 'design',
          owners: ['Sarah'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-10',
          source: 'Governance',
          sprint: 'Sprint 12',
          details: 'Create a universal template for all service landing pages ensuring consistency in layout, components, and UX patterns',
          expected_impact: 'Faster service page creation, consistent brand experience',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-3',
          title: 'UX research studies for services',
          workstream: 'product',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-20',
          source: 'Governance',
          sprint: 'Sprint 13',
          details: 'Conduct UX research studies on top service pages to identify usability issues and improvement areas',
          expected_impact: 'Evidence-based design decisions',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-4',
          title: 'Service launch checklist and process',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-08',
          source: 'Governance',
          sprint: 'Sprint 12',
          details: 'Define standardized service launch checklist covering design, content, QA, analytics, and go-live steps',
          expected_impact: 'Reduce launch issues and ensure quality',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-5',
          title: 'Content style guide for services',
          workstream: 'brand',
          owners: ['Layla', 'Content Team'],
          status: 'done',
          priority: 'p1',
          eta: null,
          source: 'Governance',
          sprint: 'Sprint 11',
          details: 'Create content style guide specific to service pages covering tone, terminology, and formatting',
          expected_impact: 'Consistent content quality across all service pages',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-6',
          title: 'QA testing protocol for service pages',
          workstream: 'tech',
          owners: ['Fatima'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-15',
          source: 'Governance',
          sprint: 'Sprint 13',
          details: 'Define QA testing protocol for service pages including cross-browser, mobile, and accessibility testing',
          expected_impact: 'Reduce post-launch bugs and improve quality',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-7',
          title: 'Service metrics KPI definitions',
          workstream: 'strategy',
          owners: ['Ahmed', 'Fatima'],
          status: 'in_progress',
          priority: 'p0',
          eta: '2026-05-05',
          source: 'Governance',
          sprint: 'Sprint 12',
          details: 'Define KPIs for each service (conversion rate, booking rate, NPS, revenue per visit)',
          expected_impact: 'Clear success metrics for service performance',
          sheet_tab: 'Governance',
        },
        {
          item_number: 'GOV-8',
          title: 'Cross-team dependency management process',
          workstream: 'ops',
          owners: ['Ahmed'],
          status: 'not_started',
          priority: 'p1',
          eta: '2026-05-20',
          source: 'Governance',
          sprint: 'Sprint 13',
          details: 'Establish process for managing cross-team dependencies between design, tech, content, and ops teams',
          expected_impact: 'Reduce delays caused by cross-team blockers',
          sheet_tab: 'Governance',
        },
      ],
    },
  ]
}
