// transcript-parser.ts
// Parser for Google Meet transcripts generated by Gemini
// Handles both raw markdown AND Google Docs text export (which strips/alters formatting)

export type ParsedAttendee = {
  name: string
  email: string
}

export type ParsedDecision = {
  text: string
  alignment: 'aligned' | 'needs_discussion'
}

export type ParsedActionItem = {
  owners: string[]
  title: string
  description: string
}

export type ParsedDiscussion = {
  topic: string
  summary: string
}

export type ParsedTranscript = {
  title: string
  date: string | null
  attendees: ParsedAttendee[]
  summary: string
  decisions: ParsedDecision[]
  actionItems: ParsedActionItem[]
  discussions: ParsedDiscussion[]
}

/**
 * Parse a raw Google Meet / Gemini transcript into structured data.
 */
export function parseTranscript(rawText: string): ParsedTranscript {
  const date = parseDate(rawText)
  const title = parseTitle(rawText)
  const attendees = parseAttendees(rawText)

  const sections = splitSections(rawText)

  const summary = parseSummary(sections['Summary'] ?? sections['summary'] ?? '')
  const decisions = parseDecisions(sections['Decisions'] ?? sections['decisions'] ?? '')
  const actionItems = parseNextSteps(sections['Next steps'] ?? sections['Next Steps'] ?? sections['next steps'] ?? sections['Action items'] ?? sections['Action Items'] ?? '')
  const discussions = parseDetails(sections['Details'] ?? sections['details'] ?? '')

  return {
    title,
    date,
    attendees,
    summary,
    decisions,
    actionItems,
    discussions,
  }
}

// ---------------------------------------------------------------------------
// Internal parsers
// ---------------------------------------------------------------------------

function parseDate(raw: string): string | null {
  const match = raw.match(
    /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},\s+\d{4}/m
  )
  return match ? match[0] : null
}

function parseTitle(raw: string): string {
  // Try ## header first (markdown)
  const mdMatch = raw.match(/^##\s+(.+)$/m)
  if (mdMatch) return mdMatch[1].trim()

  // Google Docs export: title is often the first non-empty, non-date line
  const lines = raw.split('\n').filter(l => l.trim())
  for (const line of lines) {
    const trimmed = line.trim()
    // Skip date lines, "Invited" lines, short metadata
    if (/^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d/i.test(trimmed)) continue
    if (/^Invited\s+/i.test(trimmed)) continue
    if (/^(Summary|Decisions|Next steps|Details|###)/i.test(trimmed)) continue
    if (trimmed.length < 5) continue
    return trimmed
  }
  return ''
}

function parseAttendees(raw: string): ParsedAttendee[] {
  const invitedLine = raw.match(/^Invited\s+(.+)$/m)
  if (!invitedLine) return []

  const attendees: ParsedAttendee[] = []

  // Try markdown link format: [Name](mailto:email)
  const mdRegex = /\[([^\]]+)\]\(mailto:([^)]+)\)/g
  let m: RegExpExecArray | null
  while ((m = mdRegex.exec(invitedLine[1])) !== null) {
    attendees.push({ name: m[1].trim(), email: m[2].trim() })
  }

  // If no markdown links found, try Google Docs plain text format:
  // "Name (email@domain.com)" or just comma-separated names
  if (attendees.length === 0) {
    const plainRegex = /([^,()]+?)\s*\(([^)]+@[^)]+)\)/g
    while ((m = plainRegex.exec(invitedLine[1])) !== null) {
      attendees.push({ name: m[1].trim(), email: m[2].trim() })
    }
  }

  return attendees
}

/**
 * Split the transcript on section headers into a map of section name -> content.
 * Handles:
 *   - Markdown: ### Summary
 *   - Google Docs export: Summary (as a standalone line, possibly bold)
 *   - Google Docs export with unicode: **Summary** or just SUMMARY
 */
function splitSections(raw: string): Record<string, string> {
  const sections: Record<string, string> = {}
  const knownSections = ['Summary', 'Decisions', 'Next steps', 'Next Steps', 'Action items', 'Action Items', 'Details']

  // Strategy 1: Split on ### headers (original markdown)
  const mdParts = raw.split(/^###\s+/m)
  if (mdParts.length > 1) {
    for (let i = 1; i < mdParts.length; i++) {
      const newlineIdx = mdParts[i].indexOf('\n')
      if (newlineIdx === -1) {
        sections[mdParts[i].trim()] = ''
      } else {
        const name = mdParts[i].substring(0, newlineIdx).trim()
        const body = mdParts[i].substring(newlineIdx + 1)
        sections[name] = body
      }
    }
    return sections
  }

  // Strategy 2: Google Docs plain text export — look for known section names as standalone lines
  const lines = raw.split('\n')
  let currentSection: string | null = null
  let currentBody: string[] = []

  for (const line of lines) {
    const trimmed = line.trim()
    // Remove markdown bold markers or leading #
    const cleaned = trimmed.replace(/^\*\*|\*\*$/g, '').replace(/^#+\s*/, '').trim()

    // Check if this line is a section header
    const matchedSection = knownSections.find(
      s => cleaned.toLowerCase() === s.toLowerCase()
    )

    if (matchedSection) {
      // Save previous section
      if (currentSection) {
        sections[currentSection] = currentBody.join('\n')
      }
      currentSection = matchedSection
      currentBody = []
      continue
    }

    if (currentSection) {
      currentBody.push(line)
    }
  }

  // Save last section
  if (currentSection) {
    sections[currentSection] = currentBody.join('\n')
  }

  return sections
}

function parseSummary(section: string): string {
  return section.trim()
}

function parseDecisions(section: string): ParsedDecision[] {
  if (!section.trim()) return []

  const decisions: ParsedDecision[] = []

  // Strip Google's feedback/rating text that appears before the actual decisions
  // e.g. "We've updated the Decisions section using your feedback."
  // and "Let us know what you think: Helpful or Not Helpful"
  const lines = section.split('\n')
  let currentAlignment: 'aligned' | 'needs_discussion' | null = null

  for (const line of lines) {
    const trimmed = line.trim()

    // Skip Google feedback lines
    if (/^We've updated|^Let us know what you think|^\[?Helpful\]?|^\[?Not Helpful\]?/i.test(trimmed)) {
      continue
    }
    // Skip empty lines and URLs
    if (!trimmed || /^https?:\/\//i.test(trimmed)) continue

    if (/^ALIGNED$/i.test(trimmed)) {
      currentAlignment = 'aligned'
      continue
    }
    if (/^NEEDS FURTHER DISCUSSION$/i.test(trimmed)) {
      currentAlignment = 'needs_discussion'
      continue
    }

    // Match bullet points: "  - Text here" or "- Text here" or "* Text here"
    const bulletMatch = line.match(/^\s*[-*]\s+(.+)$/)
    if (bulletMatch && currentAlignment) {
      // Clean up any trailing markdown links or artifacts
      const text = bulletMatch[1].trim().replace(/\s*\[.*?\]\(.*?\)\s*$/, '')
      if (text.length > 5) {
        decisions.push({
          text,
          alignment: currentAlignment,
        })
      }
    }

    // Also try non-bulleted lines that look like decision content
    // (Google Docs sometimes removes the bullet formatting)
    if (!bulletMatch && currentAlignment && trimmed.length > 15 && !trimmed.startsWith('#')) {
      // Avoid adding header-like or metadata lines
      if (!/^(ALIGNED|NEEDS|We've|Let us|Helpful|Not)/i.test(trimmed)) {
        decisions.push({
          text: trimmed,
          alignment: currentAlignment,
        })
      }
    }
  }

  return decisions
}

function parseNextSteps(section: string): ParsedActionItem[] {
  if (!section.trim()) return []

  const items: ParsedActionItem[] = []

  // Strip Google feedback text from Next steps too
  const cleanedSection = section.replace(/We've updated.*?feedback\.\s*/gi, '')
    .replace(/Let us know what you think:.*$/gm, '')

  // Try escaped brackets first: \[Owner Names\] Title: Description
  const escapedRegex = /^\s*-\s*\\\[([^\]]+)\\\]\s*(.+?):\s*(.+)$/gm
  let m: RegExpExecArray | null
  while ((m = escapedRegex.exec(cleanedSection)) !== null) {
    const owners = m[1].split(',').map((o) => o.trim()).filter(Boolean)
    items.push({
      owners,
      title: m[2].trim(),
      description: m[3].trim(),
    })
  }

  // If no escaped brackets found, try unescaped brackets: [Owner Names] Title: Description
  if (items.length === 0) {
    const unescapedRegex = /^\s*[-*]\s*\[([^\]]+)\]\s*(.+?):\s*(.+)$/gm
    while ((m = unescapedRegex.exec(cleanedSection)) !== null) {
      const owners = m[1].split(',').map((o) => o.trim()).filter(Boolean)
      items.push({
        owners,
        title: m[2].trim(),
        description: m[3].trim(),
      })
    }
  }

  // Strategy 3: Google Docs plain text - Owner Name(s) may be at start without brackets
  // Format: "- Owner Name: Title - Description" or "Owner Name: Action item text"
  if (items.length === 0) {
    const plainRegex = /^\s*[-*]\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*(?:\s*,\s*[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)*)\s*[:]\s*(.+?)(?:\s*[:]\s*(.+))?$/gm
    while ((m = plainRegex.exec(cleanedSection)) !== null) {
      const owners = m[1].split(',').map((o) => o.trim()).filter(Boolean)
      if (m[3]) {
        items.push({ owners, title: m[2].trim(), description: m[3].trim() })
      } else {
        // Single colon format: "Owner: full description"
        const fullText = m[2].trim()
        const dashIdx = fullText.indexOf(' - ')
        if (dashIdx > 0) {
          items.push({ owners, title: fullText.substring(0, dashIdx).trim(), description: fullText.substring(dashIdx + 3).trim() })
        } else {
          items.push({ owners, title: fullText, description: '' })
        }
      }
    }
  }

  return items
}

function parseDetails(section: string): ParsedDiscussion[] {
  if (!section.trim()) return []

  const discussions: ParsedDiscussion[] = []
  const bulletRegex = /^\s*[-*]\s+(.+?):\s*(.+)$/gm
  let m: RegExpExecArray | null
  while ((m = bulletRegex.exec(section)) !== null) {
    discussions.push({
      topic: m[1].trim(),
      summary: m[2].trim(),
    })
  }
  return discussions
}

// ---------------------------------------------------------------------------
// Category suggestion helper
// ---------------------------------------------------------------------------

const CATEGORY_KEYWORDS: [RegExp, string][] = [
  [/\b(babysitter|nanny|sitter|carer)\b/i, 'babysitter-nanny'],
  [/\b(party|birthday|balloonizer)\b/i, 'birthday-party-planning'],
  [/\b(wallpaper|nursery\s+room|kids\s+room)\b/i, 'wallpaper'],
  [/\b(health|doctor|altibbi|telehealth|teleconsultation)\b/i, 'teleconsultation'],
  [/\b(clean|healthy\s+home|thh|pest)\b/i, 'healthyhome-thh'],
  [/\b(interior|kids\s+interior)\b/i, 'kids-interior-design'],
  [/\b(tutor)\b/i, 'tutor-at-home'],
  [/\b(midwife)\b/i, 'midwife'],
  [/\b(gear)\b/i, 'gear-refresh'],
  [/\b(GA|analytics|tracking)\b/i, 'general-platform'],
]

/**
 * Given a text snippet (e.g. a decision or action item), suggest the most
 * likely service category based on keyword matching. Returns null if no
 * category can be inferred.
 */
export function suggestCategory(text: string): string | null {
  for (const [pattern, category] of CATEGORY_KEYWORDS) {
    if (pattern.test(text)) {
      return category
    }
  }
  return null
}
